https://example.com/comments/1


### Valid email addresses

POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"email": "testemail@st-andrews.ac.uk",
	"password": "fakepassword",
	"userStatus": "u1",
	"userName": "Tamim Azmain"
}

### Invalid email addresses
POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"email": "maat1fasdnfsadfasf@gmail.com",
	"password": "",
	"userStatus": "u1",
	"userName": "Tamim Azmain"
}


### Valid Login Request
POST http://localhost:8080/auth/login
Content-Type: application/json

{
	"email": "testemail@st-andrews.ac.uk",
	"password": "fakepassword"
}

### Request new access token with refresh token
POST http://localhost:8080/auth/token
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsIm5hbWUiOiJUYW1pbSBBem1haW4iLCJlbWFpbCI6InRlc3RlbWFpbEBzdC1hbmRyZXdzLmFjLnVrIiwicGFzc3dvcmQiOiJlNjgwOGE1NmFhZDY2Y2Y4OWI0MzM4OGVmM2QwZjAyMTIwNjU5NDM5OWRjZDZjMWI3MGQ4MzgyYTFkYWU0MDJiIiwic3RhdHVzIjoidTEiLCJpc0FjdGl2ZSI6MSwiY3JlYXRlZEF0IjoiMjAyMS0wNy0xNFQxNjoxMTo0OC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wNy0xNFQxNjoxMTo0OC4wMDBaIiwiaWF0IjoxNjI2MjgzOTMwfQ.hBK_uXwC4jYkZ82XsHN9DMjQMCroUzCxvpXA_Op4sFg"
}


### Fetch dummy data with no refresh token -- should be blocked
GET http://localhost:8080/work/dummy
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsIm5hbWUiOiJUYW1pbSBBem1haW4iLCJlbWFpbCI6InRlc3RlbWFpbEBzdC1hbmRyZXdzLmFjLnVrIiwicGFzc3dvcmQiOiJlNjgwOGE1NmFhZDY2Y2Y4OWI0MzM4OGVmM2QwZjAyMTIwNjU5NDM5OWRjZDZjMWI3MGQ4MzgyYTFkYWU0MDJiIiwic3RhdHVzIjoidTEiLCJpc0FjdGl2ZSI6MSwiY3JlYXRlZEF0IjoiMjAyMS0wNy0xNFQxNjoxMTo0OC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wNy0xNFQxNjoxMTo0OC4wMDBaIiwiaWF0IjoxNjI2MjgzOTMwLCJleHAiOjE2MjYzNzAzMzB9.VyWgqO4E1uKHK9TsXI54TVrIuAU08b2l9d17VK1Zq7w

{
	"data": "stuff"
}

### Add new Encounter
# DEFINITION: 
# const {
#         encounterNumber, NONNULL
#         speciesName, NONNULL
#         latitude,
#         longitude,
#         country, NONNULL
#         region, NONNULL
#         distanceFromSurveyVessel,
#         description, DEFAULT ""
#         flag, DEFAULT 1 (represents uncommitted add)
#     }

POST http://localhost:8080/encounter/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsIm5hbWUiOiJUYW1pbSBBem1haW4iLCJlbWFpbCI6InRlc3RlbWFpbEBzdC1hbmRyZXdzLmFjLnVrIiwicGFzc3dvcmQiOiJlNjgwOGE1NmFhZDY2Y2Y4OWI0MzM4OGVmM2QwZjAyMTIwNjU5NDM5OWRjZDZjMWI3MGQ4MzgyYTFkYWU0MDJiIiwic3RhdHVzIjoidTEiLCJpc0FjdGl2ZSI6MSwiY3JlYXRlZEF0IjoiMjAyMS0wNy0yOVQxMzo0NTo1OS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wNy0yOVQxMzo0NTo1OS4wMDBaIiwiaWF0IjoxNjI4MzQ4MDQ0LCJleHAiOjE2MjgzODQwNDR9.-VPn4UuCCVCPXU5K0BEeSi5cbtsQO87F6-xnccCj9_8

{
	"encounterNumber": "1",
	"speciesName": "Homo sapiens",
	"country" : "Japan",
	"region" : "Yokosuka",
	"distanceFromSurveyVessel" : "30km",
	"description" : "This is just some test data that I forgot to delete. Please ignore me."
}

##### Upload a file

POST http://localhost:8080/work/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsIm5hbWUiOiJUYW1pbSBBem1haW4iLCJlbWFpbCI6InRlc3RlbWFpbEBzdC1hbmRyZXdzLmFjLnVrIiwicGFzc3dvcmQiOiJlNjgwOGE1NmFhZDY2Y2Y4OWI0MzM4OGVmM2QwZjAyMTIwNjU5NDM5OWRjZDZjMWI3MGQ4MzgyYTFkYWU0MDJiIiwic3RhdHVzIjoidTEiLCJpc0FjdGl2ZSI6MSwiY3JlYXRlZEF0IjoiMjAyMS0wNy0xNFQxNjoxMTo0OC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMS0wNy0xNFQxNjoxMTo0OC4wMDBaIiwiaWF0IjoxNjI3NTQzMzY2LCJleHAiOjE2Mjc1NzkzNjZ9.53YQ_Xa52gBzdbh6CpmysuE4ediSd9kltum6jkYEWyQ

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="annotation_work.zip"
Content-Type: application/zip

< ../resouces/annotation_work.zip

------WebKitFormBoundary7MA4YWxkTrZu0gW--
